// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSpaces() {
  return window['go']['desktop']['App']['GetSpaces']();
}

export function Greet(arg1) {
  return window['go']['desktop']['App']['Greet'](arg1);
}
